name: Deploy Next.js app to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Clean and install dependencies
        run: |
          npm cache clean --force
          npm ci --legacy-peer-deps

      - name: Build Next.js app
        run: |
          npm run build
          mkdir -p deploy
          cp -r .next node_modules package.json next.config.js public deploy/

      - name: Fix permissions for Next.js binary
        run: chmod +x deploy/node_modules/.bin/next

      - name: Zip deployment package
        run: cd deploy && zip -r ../deploy.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bnoon'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: deploy.zip
